#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

bool table[400][600];

class grafixMask {
public:
	vector <int> sortedAreas(vector <string> rectangles) {
        for (int i = 0; i < 400; ++i)
            for (int j = 0; j < 600; ++j)
                table[i][j] = false;
        for (int i = 0; i < (int)rectangles.size(); ++i) {
            istringstream is(rectangles[i]);
            int xa, ya, xb, yb;
            is >> xa >> ya >> xb >> yb;
            for (int x = xa; x <= xb; ++x)
                for (int y = ya; y <= yb; ++y)
                    table[x][y] = true;
        }
        vector<int> res;
        for (int i = 0; i < 400; ++i) {
            for (int j = 0; j < 600; ++j) {
                int count = sortedAreasHelper(i, j);
                if (count > 0) res.push_back(count);
            }
        }
        sort(res.begin(), res.end());
        return res;
	}

    int sortedAreasHelper(int i, int j) {
        int count = 0;
        if (table[i][j]) return count;
        table[i][j] = true;
        ++count;
        queue<pair<int, int> > qs;
        qs.push(make_pair(i, j));
        while (!qs.empty()) {
            pair<int, int> n = qs.front();
            qs.pop();
            i = n.first, j = n.second;
            if (i+1 < 400 && !table[i+1][j]) {
                table[i+1][j] = true;
                qs.push(make_pair(i+1, j));
                ++count;
            }
            if (i-1 >= 0 && !table[i-1][j]) {
                table[i-1][j] = true;
                qs.push(make_pair(i-1, j));
                ++count;
            }
            if (j+1 < 600 && !table[i][j+1]) {
                table[i][j+1] = true;
                qs.push(make_pair(i, j+1));
                ++count;
            }
            if (j-1 >= 0 && !table[i][j-1]) {
                table[i][j-1] = true;
                qs.push(make_pair(i, j-1));
                ++count;
            }
        }
        return count;
    }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, vector <int> p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	grafixMask *obj;
	vector <int> answer;
	obj = new grafixMask();
	clock_t startTime = clock();
	answer = obj->sortedAreas(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p1.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << p1[i];
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << answer[i];
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p1.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p1[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	vector <int> p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"0 292 399 307"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {116800,116800};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
    {
    // ----- test 1 -----
    string t0[] = {"48 192 351 207","48 392 351 407","120 52 135 547","260 52 275 547"};
            p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    int t1[] = {22816,192608};
            p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------
    }
    
    {
    // ----- test 2 -----
    string t0[] = {"0 192 399 207","0 392 399 407","120 0 135 599","260 0 275 599"};
            p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    int t1[] = {22080,22816,22816,23040,23040,23808,23808,23808,23808};
            p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------
    }
    
    {
    // ----- test 3 -----
    string t0[] = {"50 300 199 300","201 300 350 300","200 50 200 299","200 301 200 550"};
            p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    int t1[] = {1,239199};
            p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------
    }
    
    {
    // ----- test 4 -----
    string t0[] = {"0 20 399 20","0 44 399 44","0 68 399 68","0 92 399 92","0 116 399 116","0 140 399 140","0 164 399 164","0 188 399 188","0 212 399 212","0 236 399 236","0 260 399 260","0 284 399 284","0 308 399 308","0 332 399 332","0 356 399 356","0 380 399 380","0 404 399 404","0 428 399 428","0 452 399 452","0 476 399 476","0 500 399 500","0 524 399 524","0 548 399 548","0 572 399 572","0 596 399 596","5 0 5 599","21 0 21 599","37 0 37 599","53 0 53 599","69 0 69 599","85 0 85 599","101 0 101 599","117 0 117 599","133 0 133 599","149 0 149 599","165 0 165 599","181 0 181 599","197 0 197 599","213 0 213 599","229 0 229 599","245 0 245 599","261 0 261 599","277 0 277 599","293 0 293 599","309 0 309 599","325 0 325 599","341 0 341 599","357 0 357 599","373 0 373 599","389 0 389 599"};
            p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
    int t1[] = {15,30,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,100,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,200,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,230,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345};
            p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------
    }
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
